### ISSUE TITLE
Windows VScode support WITH INLINE JINJA CHECKING

### ISSUE THREAD

**Issue by RHCEv3** [ansible/vscode-ansible#1102]
### Problem

I work for a US Federal government agency so all you get in win10 and that's it.  Where is the plug-in I can use that does code checking INCLUDING INLINE J2 checking ad I use an EXTENSIVE amount of JU2 inline (mostly in Var sections).

I also can't use the Ansible vault either.  It's been 5 YEARS now and this BASIC TASK has NOT been done.  For Puppet there were IDEs as early a Sat6.1!

I run ONLY NATIVE Linux on ALL my personal devices since 2005 and think there should long ago have been a corperate Linux desktop but that's not the world we live in so where is my plug in for VScode OR AND ONLINE GIVERNMENT APPROVED IDE????

### Solution

Get ansible-lint ported to windows and make the VScode plug-in for Ansible able to understand and parse/check inline Jinja

### Alternatives

There are none.  I can cobble together a very old plug-in and mash it with a bunch of others but still is not good at all.

### Additional context

Unless you are TRYING TO GET US GOVERNMENT AGENCIES TO GO TO TERRAFORM, VMware, and HASHICORM VAULT you need to get these basics working for VScode ON WINDOWS.

**Comment by ssbarnea** [comment]
@RHCEv3 ansible-lint relies on ansible-core core, so porting to native Windows will not happen but you should be able to use them via either WSL or execution environments if a container engine is available.

If you are on a Windows machine that cannot enable WSL and neither have container engines installed, you will not be able to run ansible tools locally. Still, even in this case you can go for a remote approach if you have access to a remote linux box.

Another option will be to make use of code-space or dev-spaces, and run vscode inside the browser, but somehow I have the impression that a government agency might need special approvals for allowing to run code on the cloud.

I will close the ticket because at this moment it is not actionable and we know for sure that native Windows support is not planned.

**Comment by RHCEv3** [comment]
No, can NOT run anything in cloud.  Also NO WSL is NOT allowed as we are NOT allowed ANY kind of admin rights.

The fix here then is to just create a CORRECT plug-in that does NOT require ansible to be installed.  I right now have cobbled together the very old plugin and a bunch of others but still not good at all.

THIS is why everyone is looking at and adopting Terraform I guess!   Looks like this and MANY other (if not all) US Govt agencies will be Terraform shops.  :-(

WAS REALLY hoping to avoid that learning curve but looks like I'm stuck with it based on what you are not willing/able to do for 75% of the Ansible coders out there.

AND I KNOW IT CAN BE DONE because If I pay $6/month I CAN get a IntelliJ plug in that DOES run on windows.  Unfortunately intyellij for some reason is NOT on the approved software list but VSCode is.
