### ISSUE TITLE
[vscode client] Add execution environment related client configuration options

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#151]
### Problem

Add execution environment related client configuration options

### Solution

Add client configuration options for execution environments like image-name, volume mount path, host current working directory, container runtime and so on

**Comment by danielo515** [comment]
Hello.
For me it is very important to be able to configure volume mount paths. I'm currently executing this extension on a visual studio code server, running inside a docker container with access to the docker socket. Because that, the mounts are on the external (host) machine, and the ones this extension is providing are wrong because they are relative to the container. I really need to configure those to be able to use this extenson effectively.
