### ISSUE TITLE
Bug: FQCN switch does not work as expected

### ISSUE THREAD

**Issue by dschier-wtd** [ansible/vscode-ansible#176]
### Summary

First, let me thank you for the extension. Most stuff works fine for me :)

I have opted to use the FQCN all the time (including for ansible.builtin, etc.). There is also an option in the extension (ansible.ansible.useFullyQualifiedCollectionNames), which should change the behaviour to use fqcn for all auto-completion. Unfortunately, this is not the case.

### Extension version

0.4.5

### VS Code version

1.57.1

### Ansible Version

```shell
ansible --version
ansible [core 2.11.2] 
  config file = None
  configured module search path = ['/var/home/dschier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/dschier/.venv-ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /var/home/dschier/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/home/dschier/.venv-ansible/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True
```

### OS / Environment

Fedora Linux 34, using vscodium

**Comment by priyamsahoo** [comment]
Hey @daniel-wtd, just some clarifications needed:

Are you talking about the auto-completion list that is produced? Because, the list doesn't show the suggestions with FQCN right now, but on selecting the option from the list, it completes it with FQCN (provided `ansible.ansible.useFullyQualifiedCollectionNames` is set to `true`).

I believe that on switching this option on, you must be expecting auto-completion directly based on FQCN. For example, on typing `ansible.builtin.` you must be expecting auto-completions for name of modules under `builtin`.

**Comment by daniel-wtd** [comment]
Hi,
thank you for the response. To shed some more details on this.

Autocompletion only works for simple names (the popup-suggestion and the completed module are simple named). Typing ansible.builtin. does not suggest anything nor auto-completes something :/

Since the "jump to code" feature does not work, too. I am not entirely sure if this is related to vscodium, my personal setup or else.

**Comment by priyamsahoo** [comment]
@daniel-wtd, about auto-completion on FQCNs like on `ansible.builin`, currently it does not suggest options accordingly, but we are working on this feature.

I will link the PR in this issue once it is up!
