### ISSUE TITLE
Extension not compatible with VS Code 1.25.1

### ISSUE THREAD

**Issue by stuartbloom-alvaria** [ansible/vscode-ansible#198]
### Summary

Hi sorry to be a pain, and if this has already been mentioned; but when I try to install the extension (v 0.4.5) in VS Code 1.25.1 I get asked to install it manually, and when I try to install the vsix file I get an error stating the extension is not compatile :(
![image](https://user-images.githubusercontent.com/91186412/134312505-c22e8361-be22-4fba-91e8-ec33abf8cc89.png)

Can this be fixed?

Thanks in advance

### Extension version

0.4.5

### VS Code version

1.25.1

### Ansible Version

```shell
ansible 2.10.14
  config file = None
  configured module search path = ['/home/sbloom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sbloom/.local/lib/python3.8/site-packages/ansible
  executable location = /home/sbloom/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

### OS / Environment

Windows 10, WSL (Ubuntu 20.04)

**Comment by ssbarnea** [comment]
@tomaciazek @ganeshrn Do you know which version of vscode is the oldest that we can support? This is an important question because some users use locked environments where they cannot upgrade very quickly and others may use alternative editors like codium, eclipse theia which are always behind vscode APIs.

Sadly `packages.json` does not allow comments so we cannot really mention near the version why it was needed. Probably we will need to ensure we run integration tests with newest and oldest in order to keep a decent range of versions. I remember that I had to lower the version with my old codebase in order to allow these users to use the extension.

**Comment by ssbarnea** [comment]
Just to give an update, this bug will likely be closed as won't fix as I identified that the oldest version that allows installation of the extension to be `1.26.1` and I have a WIP change to add support for that which includes some minimal tests. Likely we will even have to bump it further once we identify other issues, especially as that version is few years old already.
