### ISSUE TITLE
ansible-config dump error in console (conflict between system ansible and user installed ansible)

### ISSUE THREAD

**Issue by stuartbloom-alvaria** [ansible/vscode-ansible#306]
### Summary

When loding a yml file, i get the following error in the console:
![image](https://user-images.githubusercontent.com/91186412/141132115-94d2a858-5d0e-47db-8e88-1416cd72df64.png)
and linting, etc, does not work correctlt

### Extension version

0.6.1

### VS Code version

1.62.1

### Ansible Version

```shell
ansible 2.10.15
  config file = None
  configured module search path = ['/home/sbloom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sbloom/.local/lib/python3.8/site-packages/ansible
  executable location = /home/sbloom/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

### OS / Environment

windows 10, wsl ubuntu 20.04

**Comment by ssbarnea** [comment]
That is indeed an interesting error and I think I do have an idea why it happens. As you can see the `ansible-config` executable is installed at system level but it trying to load ansible python package from user location, not system.

Likely that system ansible is one version and user installed one is a different one, a recipe for disaster.

Now we need some more info in order to identify if a bug is involved or is just your local environment misconfiguration.

- What do you see when running `which ansible-config`?
- What happens if you run `~/.local/bin/ansible-config dump`?
- What is output of `echo $PATH`?

**Comment by stuartbloom-alvaria** [comment]
Hey Sorin

Thanks for your assistance.
here is the output of the first and last command:
![image](https://user-images.githubusercontent.com/91186412/141336390-a4a36664-e7dc-4c02-a01b-d97768687152.png)

as for the dump; i get a whole lot of configuration settings

**Comment by stuartbloom-alvaria** [comment]
Infact, I have, after being recommended by another user, to change distros, and I am now getting sligtly different errors:
![image](https://user-images.githubusercontent.com/91186412/141340917-470e3c27-24e4-4a28-82d6-bc5bcf95beb5.png)
 and
![image](https://user-images.githubusercontent.com/91186412/141340984-dd06fc62-54ac-4d7f-b475-8920a25bbf9c.png)
![image](https://user-images.githubusercontent.com/91186412/141341028-133cc4bf-fbd3-4c54-8ca5-4dc6065f5a70.png)

Thanks again for any assistance

**Comment by ssbarnea** [comment]
This is starting to become interesting because it seems that you do have `ansible-config` in path and I assume you did not customize the location of ansible-config inside extensions settings either. My expectation is that when we execute the command we would use the same PATH as the one you see on your terminal. Still the screenshots you provided makes me believe that this is not really true.

For example I am aware of some potential problem with MacoS (same platform I usually use) where GUI applications (like vscode) may not get the same PATH a terminal process.

I think we will need to provide some more output from extension in order to help people identify problems like this, like printing the PATH before trying to run commands, very important especially when the executed commands do not have full paths.

My guess is that you may be able to workaround this problem by configuring full paths for ansible-config, ansible-playbooks, ... in extension settings, as we allow users to customize them.

**Comment by ssbarnea** [comment]
If your tasks are inside a folder named `tasks/`, you should not see that error. If they are at the same level as your playbooks,... you will. The only thing that makes it treat them as tasks is the parent folder name.

Syntax check if not about `---`. AFAIK we do not require `---` anywhere.

**Comment by stuartbloom-alvaria** [comment]
amazing, thanks you @ssbarnea for your time and effort.  No issues here now, intellisense, hints, all working.

Thanks again

**Comment by ssbarnea** [comment]
I will reopen the bug because I do not think that a normal user like yourself should have to alter tool paths to make it work. If ansible works in your vscode terminal, so should the extension, w/o extra tuning.

If you are pleased about how it works, you could add a review at https://marketplace.visualstudio.com/items?itemName=redhat.ansible&ssr=false#review-details

**Comment by stuartbloom-alvaria** [comment]
sure thing, I will also keep an eye on this bug.  Thanks :)

**Comment by thomascwells** [comment]
I believe I encountered this same issue today. 

> Command failed:  /usr/bin/ansible-config dump
> /bin/sh: line 1: /usr/bin/ansible-config: No such file or directory

@ssbarnea - you mentioned reopening the issue, but it appears still closed. Was there some other resolution? 

My situation is maybe a bit different, but I think it's the same core issue. I am running VSCodium inside Flatpak on Fedora 36. 

I initially had some issues getting access to ansible inside the flatpak environment (from the terminal), but I was able to solve that using the generally recommended `flatpak-spawn` approach for overriding the default terminal. 

But now, I still get errors generated by the extension regarding not being able to find the various `ansible-*` binaries. 

I tired specifying the path to ansible in the extension settings like so: 

`"ansible.ansible.path": "/usr/bin/flatpak-spawn --host ansible",`

But that still doesn't work. Any thoughts?

**Comment by ssbarnea** [comment]
Look at what you configured, is not a path, it is a command! You cannot have arguments.

Use of flatpack or similar approaches was never planned and unless there is a direct path to the executables it will never work. We call about 10 executables from that location and all need to be in the same place.

**Comment by thomascwells** [comment]
Thanks for the reply!

Maybe instead of the path to where the binaries are located, the setting could request the path to the binaries directly? 

I tried a few more things, but couldn't ever figure out how to get it to work. I'm guessing the solution might have something to do with "mounting" the correct path via flatpak, but that's beyond my skills. 

I've since switched to using a direct install of VS Code instead of flatpak and everything works fine now (of course).

I think long-term it might be worth thinking about how to support flatpak or provide integration with things like toolbox (https://containertoolbx.org/). It seems like immutable operating systems and application deployment are increasing in popularity (SilverBlue, Fedora CoreOS, NixOS, Flatpak, Snap, etc.). Obviously the goals of Ansible are philosophically aligned with this general shift! 

However, maybe the onus should be on VS Code to better expose options for selecting which of the various available environments (host, container, remote, etc) a given extension should use. Tricky problem, but fun to think about! Obviously beyond the scope of this issue.

**Comment by akkuman** [comment]
@ssbarnea These command executions are actually the result of enabling ~/.bashrc in shell
@thomascwells @stuartbloom-alvaria In fact, vscode extensions have a different behavior

Related Links:
- https://unix.stackexchange.com/a/46856
- https://github.com/microsoft/vscode-remote-release/issues/83
- https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

So, You can check your ~/.profile, ~/.bash_profile and ~/.bashrc, etc

But it's important to note that ~/.profile is not read by bash(1), if ~/.bash_profile or ~/.bash_login exists.

This reminder can be found in ~/.profile header

So you should make sure your path is correct in ~/.bash_profile, ~/.bash_login or ~/.profile，rather than ~/.bashrc

I hope my answer will help others in the same situation 😃

**Comment by akkuman** [comment]
@ssbarnea I mean the $PATH which in environment var, like ~/.local/bin, not all ansible bin path.
