### ISSUE TITLE
Syntax highlighting broken (because incorrect 'file type' in editor)

### ISSUE THREAD

**Issue by Gaibhne** [ansible/vscode-ansible#369]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

Unfortunately, https://github.com/ansible/vscode-ansible/issues/293 was closed prematurely, because while the original reporter was helped to manually fix his problem, the problem still persists for new users with no indication other than a closed issue on the source repo as how to fix it.

To be clear: I understand how I can fix the issue for myself, but that still leaves the open issue that syntax highlighting does not work for people that I think should be addressed.

I believe the root cause is the order in which this extension and the YAML extension (also from Red Hat, which was automatically installed along with this extension for me in a fresh VSCode install) are installed. Without further testing (which I can carry out if needed) I would guess that if the user already has the YAML extension installed when installing the Ansible extension, then the Ansible extension takes 'ownership' of the `.yml` association, but that if neither extension is installed, after installing the Ansible extension, the YAML extension is installed as a dependency and then takes over the association.

### Extension version

v0.7.1

### VS Code version

1.63.2

### Ansible Version

```shell
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

### OS / Environment

Windows 10, WSL, Fedora 31, ansible-lint 5.1.3 using ansible 2.11.4

**Comment by ganeshrn** [comment]
We rely on `vscode-yaml` extension for `yaml`/`yml` files that are not `ansible` playbook or tasks files. Refer https://github.com/ansible/vscode-ansible/blob/main/package.json#L53-L124

We are working on documents to help user identify ways to enable the ansible extension for an open document. Refer
1) https://github.com/ansible/vscode-ansible/pull/343
2) https://github.com/ansible/vscode-ansible/issues/341

The language activation for an open document is done by vscode itself and currently I am not sure if there is a way in extension settings to control which language takes over in case neither extension is installed. I will try to figure it out and comment my findings here.

**Comment by netsandbox** [comment]
@Gaibhne 
> I believe the root cause is the order in which this extension and the YAML extension (also from Red Hat, which was automatically installed along with this extension for me in a fresh VSCode install) are installed. Without further testing (which I can carry out if needed) I would guess that if the user already has the YAML extension installed when installing the Ansible extension, then the Ansible extension takes 'ownership' of the .yml association, but that if neither extension is installed, after installing the Ansible extension, the YAML extension is installed as a dependency and then takes over the association.

I can't confirm this, I installed first the YAML extension and then the Ansible extension and all Ansible files are still use YAML language.

@ganeshrn 
It doesn't help the user if he must enable the Ansible language for every file.
Imagine a folder with 100 Ansible files :scream: 
So best would be if auto-detection would work out of the box.
At least you should provide an example `files.associations` block in the README.

I use this one:
```json
"files.associations": {
    "**/*playbook*.{yml,yaml}": "ansible",
    "**/defaults/*.{yml,yaml}": "ansible",
    "**/handlers/*.{yml,yaml}": "ansible",
    "**/meta/*.{yml,yaml}": "ansible",
    "**/playbooks/*.{yml,yaml}": "ansible",
    "**/requirements.{yml,yaml}": "ansible",
    "**/tasks/*.{yml,yaml}": "ansible",
    "**/vars/*.{yml,yaml}": "ansible"
}
```
This one is mainly inspired from ansible-lint's detection rules:
https://github.com/ansible-community/ansible-lint/blob/03fe3936d8015190744d3756a0a3361380a05adb/src/ansiblelint/config.py#L14-L40

**Comment by ganeshrn** [comment]
@netsandbox Yes, you are right. Updating the` files.associations` block in the README is a good suggestion. I will add can add it in separate PR. We need to do a better job in communicating how to set the VSCode to work properly with the ansible extension.

>. So best would be if auto-detection would work out of the box.

Since Ansible uses `yaml`/ `yml` extension for its file there needs to be a way in VSCode to look at the file content and identify the language to decide which extension to activate. I have not seen any VS Code document that allows us to do that. The language is set based on the file extension and file associations. Hence I doubt auto-detection will work out of the box.

On the other side defaulting every file with the `yaml`/`yml` extension as Ansible language is also not a good user experience since large chunk of YAML files in the user environment won't be Ansible and it will result in false errors.

**Comment by ssbarnea** [comment]
@netsandbox is using the same patterns as me. The goal was to add some code that reconfigures user files.associations on extension install but my first attempts to write user settings were not successful, function call worked but nothing was saved in either user or workspace settings.

That property is tricky by definition because we need to only add our associations, we cannot just override all file associations or we will make users very angry.

**Comment by ssbarnea** [comment]
Not a bug.
